### ISSUE TITLE
Can't build project: Could not resolve org.lwjgl.lwjgl:lwjgl*

### ISSUE THREAD

**Issue by AlexandrLevin-SelfTable** [calmilamsy/BIN-fabric-example-mod#1]
I running macOS 10.15.7 and trying to build a project with IntelliJ IDEA CE.

Error below is what I get when trying to build a project. This issue previously was opened [here](https://github.com/ModificationStation/StationLoader/issues/9).

Since then I have deleted the `~/.gradle/caches/fabric-loom` folder several times during the day, redownloaded the workspace, but every time I get this error:

```
A problem occurred configuring root project 'BIN-fabric-example-mod-master'.
> Failed to notify project evaluation listener.
   > Could not resolve all files for configuration ':minecraftInducedLibraries'.
      > Could not resolve org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20130708-debug3.
        Required by:
            project :
         > Could not resolve org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20130708-debug3.
            > Could not parse POM https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.1-nightly-20130708-debug3/lwjgl-2.9.1-nightly-20130708-debug3.pom
               > Could not find org.lwjgl.lwjgl:parent:2.9.1-SNAPSHOT.
                 Searched in the following locations:
                   - file:/Users/alexandrlevin/.gradle/caches/fabric-loom/parent-2.9.1-SNAPSHOT.jar
                   - file:/Users/alexandrlevin/.gradle/caches/fabric-loom/parent.jar
                   - file:/Users/alexandrlevin/Projects/BIN-fabric-example-mod-master/build/loom-cache/parent-2.9.1-SNAPSHOT.jar
                   - file:/Users/alexandrlevin/Projects/BIN-fabric-example-mod-master/build/loom-cache/parent.jar
                   - file:/Users/alexandrlevin/Projects/BIN-fabric-example-mod-master/.gradle/loom-cache/remapped_mods/parent-2.9.1-SNAPSHOT.jar
                   - file:/Users/alexandrlevin/Projects/BIN-fabric-example-mod-master/.gradle/loom-cache/remapped_mods/parent.jar
                   - https://maven.fabricmc.net/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/maven-metadata.xml
                   - https://maven.fabricmc.net/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/parent-2.9.1-SNAPSHOT.pom
                   - https://libraries.minecraft.net/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/maven-metadata.xml
                   - https://libraries.minecraft.net/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/parent-2.9.1-SNAPSHOT.pom
                   - https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/maven-metadata.xml
                   - https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/parent-2.9.1-SNAPSHOT.pom
                   - https://jcenter.bintray.com/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/maven-metadata.xml
                   - https://jcenter.bintray.com/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/parent-2.9.1-SNAPSHOT.pom
                   - https://jitpack.io/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/maven-metadata.xml
                   - https://jitpack.io/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/parent-2.9.1-SNAPSHOT.pom
      > Could not resolve org.lwjgl.lwjgl:lwjgl_util:2.9.1-nightly-20130708-debug3.
        Required by:
            project :
         > Could not resolve org.lwjgl.lwjgl:lwjgl_util:2.9.1-nightly-20130708-debug3.
            > Could not parse POM https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.1-nightly-20130708-debug3/lwjgl_util-2.9.1-nightly-20130708-debug3.pom
               > Could not find org.lwjgl.lwjgl:parent:2.9.1-SNAPSHOT.
                 Searched in the following locations:
                   - file:/Users/alexandrlevin/.gradle/caches/fabric-loom/parent-2.9.1-SNAPSHOT.jar
                   - file:/Users/alexandrlevin/.gradle/caches/fabric-loom/parent.jar
                   - file:/Users/alexandrlevin/Projects/BIN-fabric-example-mod-master/build/loom-cache/parent-2.9.1-SNAPSHOT.jar
                   - file:/Users/alexandrlevin/Projects/BIN-fabric-example-mod-master/build/loom-cache/parent.jar
                   - file:/Users/alexandrlevin/Projects/BIN-fabric-example-mod-master/.gradle/loom-cache/remapped_mods/parent-2.9.1-SNAPSHOT.jar
                   - file:/Users/alexandrlevin/Projects/BIN-fabric-example-mod-master/.gradle/loom-cache/remapped_mods/parent.jar
                   - https://maven.fabricmc.net/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/maven-metadata.xml
                   - https://maven.fabricmc.net/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/parent-2.9.1-SNAPSHOT.pom
                   - https://libraries.minecraft.net/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/maven-metadata.xml
                   - https://libraries.minecraft.net/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/parent-2.9.1-SNAPSHOT.pom
                   - https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/maven-metadata.xml
                   - https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/parent-2.9.1-SNAPSHOT.pom
                   - https://jcenter.bintray.com/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/maven-metadata.xml
                   - https://jcenter.bintray.com/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/parent-2.9.1-SNAPSHOT.pom
                   - https://jitpack.io/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/maven-metadata.xml
                   - https://jitpack.io/org/lwjgl/lwjgl/parent/2.9.1-SNAPSHOT/parent-2.9.1-SNAPSHOT.pom
   > java.lang.NullPointerException (no error message)
   > path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

What I tried already:

1. Manually download not resolved libraries from `https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.1-nightly-20130708-debug3/lwjgl-2.9.1-nightly-20130708-debug3.jar`, `https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.1-nightly-20130708-debug3/lwjgl_util-2.9.1-nightly-20130708-debug3.jar` and place them in `%project_dir%/libs`. Then I added this directory to repositories in `build.gradle` like this:
```
repositories {
	...
	flatDir {
		dirs 'libs'
	}
}
```

2. Now project built successfully, but when starting the Minecraft client with the provided run configuration I saw the following error in output:

```
Exception in thread "Minecraft main thread" java.lang.UnsatisfiedLinkError: Can't load library: /Users/alexandrlevin/.gradle/caches/fabric-loom/natives/b1.7.3/liblwjgl.dylib
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1827)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:95)
	at org.lwjgl.Sys.<clinit>(Sys.java:112)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at net.minecraft.client.Minecraft.init(Minecraft.java:244)
	at net.minecraft.client.Minecraft.run(Minecraft.java:716)
	at java.lang.Thread.run(Thread.java:748)
```

3. A also tried to rename presented in `/Users/alexandrlevin/.gradle/caches/fabric-loom/natives/b1.7.3/liblwjgl.jnilib` to `liblwjgl.dylib` then the error goes away but the game window doesn't pop up.

Any ideas on how to fix this problem?

**Comment by calmilamsy** [comment]
Try downloading lwjgl for osx (https://files.pymcl.net/client) and taking the dylibs from there and putting them in the folder the other dylibs are in.

Sorry about the late reply.
